### PR TITLE
Fix the partial save for contact containers

### LINKED ISSUE #414: Test results are wiped if you navigate to other tests and press save
Steps to replicate:

- Open Contact 1 for a new woman
- In Tests container, enter test results for all tests in the Due tab
- after entering the last test on the page (should be TB screening), click on the next button at the bottom
- then tap on the SAVE button in the top right on the Other Tests page (don't submit any test results on this page)
- Re-open the Tests container. You'll see that all of the Test results you entered are cleared and you have to start over.

### PR DESCRIPTION
**Pull request by dubdabasoduba**
Partial save didn't happen when `save` option was clicked on the contact containers. Fixes #414

### CODE REVIEW

File: opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import android.widget.Toast;
 
 import com.vijay.jsonwizard.activities.JsonFormActivity;
+import com.vijay.jsonwizard.constants.JsonFormConstants;
```
Comment (keymane) [inline opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java]: Codacy Issue found: [Avoid unused imports such as 'com.vijay.jsonwizard.constants.JsonFormConstants'](https://app.codacy.com/app/OpenSRP/opensrp-client-anc/pullRequest?prid=4647348)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/OpenSRP/opensrp-client-anc/pullRequest?prid=4647348&bid=15563598)

File: opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java [hunk 2]
```diff
@@ -118,10 +119,11 @@ public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
 
     @Override
     public boolean onOptionsItemSelected(MenuItem item) {
-        if (super.onOptionsItemSelected(item)) {
-            return true;
+        if (item.getItemId() == R.id.action_save) {
+            if (getActivity() != null) {
```
Comment (keymane) [inline opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java]: Codacy Issue found: [These nested if statements could be combined](https://app.codacy.com/app/OpenSRP/opensrp-client-anc/pullRequest?prid=4647348)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/OpenSRP/opensrp-client-anc/pullRequest?prid=4647348&bid=15563598)

File: opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java (hunk 1 above)
Comment (keymane) [inline opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java]: Codacy Issue found: [Avoid unused imports such as 'com.vijay.jsonwizard.constants.JsonFormConstants'](https://app.codacy.com/app/OpenSRP/opensrp-client-anc/pullRequest?prid=4647348)

File: opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java (hunk 2 above)
Comment (keymane) [inline opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java]: Codacy Issue found: [These nested if statements could be combined](https://app.codacy.com/app/OpenSRP/opensrp-client-anc/pullRequest?prid=4647348)
